FROM golang:alpine
MAINTAINER "HashiCorp Terraform, https://hub.docker.com/r/hashicorp/terraform/dockerfile"

ENV TERRAFORM_VERSION=0.12.5

RUN apk add --update git bash openssh

ENV TF_DEV=true
ENV TF_RELEASE=true

WORKDIR $GOPATH/src/github.com/hashicorp/terraform
RUN git clone https://github.com/hashicorp/terraform.git ./ && \
    git checkout v${TERRAFORM_VERSION} && \
    /bin/bash scripts/build.sh

WORKDIR $GOPATH
ENTRYPOINT ["terraform"]
