#K8s for Mac StorageClass

---

kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: osxstorage
provisioner: docker.io/hostpath
reclaimPolicy: Retain
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
